### ISSUE TITLE
Mental dataset

### ISSUE THREAD

**Issue by graemeleehickey** [graemeleehickey/joineR#14]
Find the source and reference + add to help file

**Comment by petephilipson** [comment]
Hi Graeme,

This dataset is an anonymised subset of the PANSS data that is analysed in Henderson, Diggle & Dobson (2000). Unlike the liver cirrhosis data this is not publicly available, I recall Rob saying that it is the property of Janssen pharmaceuticals, so for the original release of joineR we took a random sample and used the ambiguous terminology of 'mental state assessment' for the repeated measures. As such I am not sure whether we can legitimately provide a reference etc. Any protection may have lapsed, which is something we could check with Rob but I'm not confident. Options are to include it as a vaguely described dataset, or drop it (we already have some other datasets).

**Comment by graemeleehickey** [comment]
Thanks. Have found the following:

http://www.stata.com/meeting/nordic-and-baltic16/slides/norway16_marchenko.pdf

which references this dataset from Peter:

http://www.lancaster.ac.uk/staff/diggle/APTS-data-sets/PANSS_short_data.txt

So think I will just use phrasing from the latter and add Peter Diggle as the 'source'.
