### ISSUE TITLE
Issue of standard error estimation 

### ISSUE THREAD

**Issue by shanpengli** [graemeleehickey/joineR#51]
Hi,

I got an error message when I was running jointSE():

Error in solve.default(pdMatrix(a, factor = TRUE)) : 
  Lapack routine dgesv: system is exactly singular: U[1,1] = 0
In addition: There were 50 or more warnings (use warnings() to see the first 50)

warnings():
In logLik.lmeStructInt(lmeSt, lmePars) :
  Singular precision matrix in level -1, block 1

Do you know how to fix this error? Or it is data-specific issue?

Jeffrey

**Comment by graemeleehickey** [comment]
We would need a reproducible example to investigate.

**Comment by graemeleehickey** [comment]
Closing as no further response.
