### ISSUE TITLE
competing risk, multivariate

### ISSUE THREAD

**Issue by abadereddeen** [graemeleehickey/joineR#55]
I am trying to use the package in the presence of competing risk. 
I going through the issue that if I include more than one variable (x1+x2)  in the survival model, I get an error saying that object x2 is not found, 
I tried also the epileptic data and I got the same error when I tried to include gender and age in the model

`> data(epileptic)
>   
>   longitudinal <- epileptic[, c(1:3)]
>   survival <- UniqueVariables(epileptic, c(4, 6), "id")
>   baseline <- UniqueVariables(epileptic, c(“age”,”gender”), "id")
>   data <- jointdata(longitudinal = longitudinal,
>                     survival = survival,
>                     baseline = baseline,
>                     id.col = "id",
>                     time.col = "time")
>                     
>   fit2 <- joint(data = data,
>                 long.formula = dose ~ time,
>                 surv.formula = Surv(with.time, with.status2) ~ gender+age,
>                 longsep = FALSE, survsep = FALSE,
>                 gpt = 3)`
**/

_Error in eval(predvars, data, env) : object 'age' not found
In addition: Warning message:
In names(survdat2)[(ncol(survdat) + 1):ncol(survdat2)] <- attr(surv.terms,  :
  number of items to replace is not a multiple of rep
lacement _length__
```

**Comment by graemeleehickey** [comment]
I have moved the issue to here: https://github.com/petephilipson/joineR/issues/14
